apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    chart:  {{ .Values.backstage.app.chart }}
    helm:
      valueFiles:
        - {{ .Values.backstage.app.valueFile }}
    repoURL: {{ .Values.backstage.app.repoURL }}
    targetRevision: {{ .Values.backstage.app.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 15
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true