kind: Secret
apiVersion: v1
metadata:
  name: redhat-gpte-devhub-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  .dockerconfigjson: {{ .Values.backstage.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
